all:
  children:
    prod:
      vars:
        github_account: # TODO github.com/<github_account>/some_repo.git

        # Credentials for Dockerhub
        docker_username: # TODO add your ENCRYPTED Docker Hub username here
        docker_password: # TODO add your ENCRYPTED Docker Hub password here
      hosts:
        my-host:
          ansible_host: # TODO put the IP address of your remote host here
          # apps must have the same name as the corresponding Github repo
          apps:
            - hello-web-app
            - reverse-proxy
